name: Deploy to Server

on:
  push:
    branches: [ "main" ]  # oder "master", je nach deinem Branch-Namen

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Kassensystem
            git pull origin main
            # Hier weitere Befehle wie npm install, restart service etc. 